export const jokes = [
    "I'm afraid for the calendar. Its days are numbered.",
    "Why do fathers take an extra pair of socks when they go golfing?\n\nIn case they get a hole in one!",
    "What do you call a factory that makes okay products?\n\nA satisfactory.",
    "What did the ocean say to the beach?\n\nNothing, it just waved.",
    "What did the zero say to the eight?\n\nThat belt looks good on you.",
    "What's the best thing about Switzerland?\n\nI don't know, but the flag is a big plus.",
    "Why don't eggs tell jokes?\n\nThey'd crack each other up.",
    "I have a joke about chemistry, but I don't think it will get a reaction.",
    "Did you hear about the guy who invented the knock-knock joke?\n\nHe won the 'no-bell' prize.",
    "I like telling Dad jokes. Sometimes he laughs!",
    "I ordered a chicken and an egg online. I’ll let you know.",
    "I was going to tell a time-traveling joke, but you guys didn't like it.",
    "Mountains aren't just funny. They're hill areas.",
    "Wanna hear a joke about paper? Never mind—it's tearable.",
    "Don't trust atoms. They make up everything!",
    "When does a joke become a dad joke? When it becomes apparent.",
    "What do you call a Frenchman wearing sandals? Philippe Flop",
    "I don’t get why Marvel doesn’t use the Hulk to advertise more. He’s basically one big Banner.",
    "I just found out I’m colorblind. The news came out of the purple!",
    "What's the difference between a well-dressed man on a unicycle and a poorly-dressed man on a bicycle?\n\nAttire.",
    "This year’s Fibonacci convention is going to be really special!\n\nApparently it’s as big as the last two put together.",
]